name: localink
description: "A new localink project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  pinput: ^4.0.0
  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  logging: ^1.2.0
  geolocator: ^14.0.2
  geocoding: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7

  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/icons.png
    - assets/icons2.png

  uses-material-design: true
flutter_native_splash:
  color: "#ffffff"
  image: assets/app_logo_final.png # Path to your logo
  android_12:
    image: assets/app_logo_final.png
    color: "#ffffff"
    icon_background_color: "#ffffff"
  web: false